pages=[OCRPageObject(index=0, markdown='# TUTTOSTORT \n\n## Cambio tattico\n\nDopo anni di proficua collaborazione il dinamico duo Compagna-Napolitano viene rilevato da una cooperativa di giovani e promettenti cronisti alle prime armi (noi). Gli aficionados del vecchio e glorioso Tuttostort non rimarranno delusi; la nuova redazione cercherà infatti di mantenere inalterate
 le caratteristiche che hanno reso famoso il vecchio giornale aggiornandolo e, se possibile, migliorandolo. Facciamo nostro l\'augurio dei maestri Compagna e Napolitano: Tuttostort non bisogna per forza leggerlo, basta comprarlo.\n\n## Abbattuta la palma di Patrizi. Fine di un mito!\n\nEsclusivo! Intervista al proviseur sui motivi del tragico intervento.\n\nDa sempre simb
olo del Lycée Chateaubriand, la palma che da più di cent\'anni dominava il cortile della sede di Via di Villa Patrizi, è stata cancellata dal panorama generale al quale erano oramai abituati gli alunni del Lycée. Per due settimane lo spazio sottostante l\'albero è stato recintato per evitare rischi. In effetti, in primavera, dopo un lungo nobiltagio, un\'altro albero dell
a cour è caduto, e per giunta invadendo l\'area della scuola svizzera. Prima di prendere la sofferta decisione, l\'amministrazione deve anche aver pensato alla diplomazia, e alla scena improbabile in cui gli alunni del Lycée si arrampicano sul muro di divisione gridando: "Ci ridate la palma?"\n\n## A riflettori accesi, due grandi squadre fanno vedere grandi cose. PERO\', 
CHE CALCIO!\n\nS.P.Q.R e Barjots giocano una partita vera. Finisce 2 a 1 per gli ex ma Keita e compagni non si arrendono prima del quarantesimo.\n\nPorci e Alka Seltzer danno vita ad un match combattuto.\n\n## EX RIMONTATI\n\nUn grande Busby non basta a far vincere la partita ai Porci che, in vantaggio 4 a 1 , si fanno rimontare da Giagni e compagni. Finisce 5 a 5; un par
eggio giusto.\n\nTre big match in prima giornata. Completa il quadro quello del gruppo A.\nI PROFS CI INSEGNANO A GIOCARE A... TENNIS.\nUn Grellier onnipotente permette ai Profs di "liquidare" i Divina Commedia 7 a 5.\n\nAll\'interno:\nCalendario completo: gironi A, B e C. Composizione completa delle squadre. Regolamento ufficiale.\n\nAltri risultati:\nYubikai - Rinko Boy
s: 11 - 4\nChrismateras Stars - Ploucs: 3 - 2\nCurva Nord - The Angels: 2 - 3\nDominata da Ruggeri (Yubikai) la classifica marcatori con 5 gol.', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=1, markdown='# La palma di Patrizi abbattuta, al suo posto un\' ingloriosa seminana. UNA DECISIONE SOFFERTA! \n\n## "...Ma sono stat
o obbligato."\n\nQuando il nostro inviato ci ha detto di aver strappato un appuntamento per un\'intervista esclusiva con il proviseur, gli abbiamo presentato subito le nostre condoglianze. Pensate cari lettori, un quarto d\'ora in faccia a faccia, in un bureau nel quale nessuno ha mai messo piede se non con gravi precedenti penali, e, di solito, chi riesce ad entrare in q
uel tempio sacro che è la stanza dei bottoni del Lycée, difficilmente ne esce. Quando il nostro impavido cronista varcò la doppia porta che separa la stanza da quella della-segreteria, gli parve di leggere "Lasciate ogni speranza voi ch\'entrate". Grazie al solido appoggio del CPE M. Sénéchal, il nostro è uscito un po\' scosso ma bene in vita, pronto a rivelare la verità,
 tutta la verità, nient\'altro che la verità sul misterioso abbattimento della palma di Patrizi. Saranno delusi i soliti sovversivi che speravano si trattasse di una deliberata provocazione della nuova amministrazione Thomas ancora fresca di nomina. Ecco come si svolsero effettivamente i fatti:\n"La palma è stata abbattuta perchè presentava dei grossi rischi di incidente:
 la parte superiore e gran parte del tronco erano cave sia perché l\'albero era malato, sia perché dei simpatici volatili (li possino ammazza\' $n d r$ ) lo avevano ripetutamente beccato. Avevamo fatto venire degli specialisti per vedere se era possibile salvarla, ci hanno detto, in virtù anche del fatto che la palma era spesso attorniata da nugoli di alunni: bisogna rade
rla al suolo.\n\nAbbiamo immediatamente inoltrato la domanda ufficiale; l\'iter burocratico è stato lungo, per questo la cour sottostante l\'albero è stata negata agli alunni per ben 15 giorni. Erano necessarie sette firme. Appena ottenuta l\'ultimo sigillo, abbiamo proceduto non senza rimorso, al doloroso abbattimento per evitare di correre rischi inutili. La legge ci ob
bliga - e personalmente ritengo sia giusto - a ripiantare una palma al suo posto; l\'operazione è stata portata a termine con successo cosicché la cour sfoggia di nuovo una palma anche se solo di 2-3 metri.\n\nQuella di abbattere la pianta-simbolo del Lycée Chateaubriand (in effetti anche Malpighi ha la propria), è stata più che mai una decisione sofferta ma, ahimé, neces
saria. Mi è parso spiacevole dover, dopo solo un mese e mezzo di mandato al Lycée, radere al suolo una palma, immagine del Lycée, che domina questa cour da più di cent\'anni, ma sono stato obbligato."\n\nIl nostro inviato, a questo punto, trova il coraggio di farfugliare una domanda:\n"Lei ha visitato e diretto molti istituti; immagino sia la prima volta che si trova a do
versi confrontare con problemi di tipoambientale, vista anche la delicata gestione della Villa StrohlFern..."\n\nQui il proviseur sfodera un\'espressione tra il soddisfatto, come se fosse la domanda che aspettava, e il sorpreso, per il modo alquanto sgrammaticato nel quale gli è stata posta.\n"E esattamente quello che fa l\'interesse di questa carica: vedere delle situazi
one nuove e dei problemi diversi, affrontare un contesto nuovo con degli interlocutori nuovi, c\'est l\'intérêt du métier."\n![img-0.jpeg](img-0.jpeg)', images=[OCRImageObject(id='img-0.jpeg', top_left_x=172, top_left_y=1808, bottom_right_x=1485, bottom_right_y=2212, image_base64=None)], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=
2, markdown='| GIRONE A | GIRONE B |\n| :-- | :-- |\n| Profs - Divina Commedia: 7 - 5 | Porci - Alka Seltzer: 5 - 5 |\n| Yubikai - Rinko Boys: 11 - 4 | Chrismateras Stars - Ploucs: 3 - 2 |\n| Riposa: Black Eagle. | Riposa: Napalm. |\n| YUBIKAI | 3 |\n| PROFS | 3 |\n| DIVINA COMMEDIA | 0 |\n| RINKO BOYS | 0 |\n| BLACK EAGLE | $0^{*}$ |\n\n\n| GIRONE C |\n| :-- |\n| S.P.Q.R
 - Barjots: 2 - 1 |\n| Curva Nord - The Angels: 2 - 3 |\n| Riposa: Grunges A.C. |\n| THE ANGELS 3 |\n| S.P.Q.R. 3 |\n| CURVA NORD 0 |\n| BARJOTS 0 |\n| GRUNGES A.C.* 0* |\n\n# CLASSIFICA \n\nMARCATORI:\n\n| 5 - | RUGGERI (Yubikai) |\n| :-- | :-- |\n|  |  |\n| 3 - | BALDANZA (Porci) |\n|  | GLAGNI (Alka Seltzer) |\n|  | GRELLIER (Profs) |\n|  | SFARA (Divina Commedia) |\n|
  | UBERTI (Yubikai) |\n|  |  |\n| 2 - | BOUBLIL (Christmateras Stars) |\n|  | MARENCO (Rinko Boys) |\n|  | MIELI (Alka Seltzer) |\n|  | POGLIANI (Curva Nord) |\n|  | SCALABRINI (The Angels) |\n|  | TREILLES (Profs) |\n\n## LA NAZIONALE DEL MERCOLEDI\n\nIn questa nazionale elenchiamo i migliori giocatori per ruolo secondo i voti dei giornalisti del TUTTOSTORT. Escludiamo 
i calciatori delle tre squdre teste di serie perché ex o "laureati" e quindi non più selezionabili dal mister Treilles.\n\nPortiere: SABATINO (Ploucs) 7,5\nDifensore: CARPI (The Angels) 7+\nCentrocampista: SCALABRINI (The Angels) 7,5++\nPunta: POGLIANI (Curva Nord) 7+\nQuinto uomo*: GLAGNI (Alka Seltzer) 7,5\n\n* Quinto uomo sta per uomo in più che svaria su tutto il camp
o senza posizione fissa.\n\n\n## IL PUNTO\n\nUna giornata, la prima, caratterizzata da tre Big Matches Profs-Divina Commedia, Porci-Alka Seltzer e S.P.Q.R. Barjots. Tre bellissime partite, specialmente la terza.\n\nGruppo A:\nLa facilità con la quale i Profs si sono liberati dei divina Commedia (ancora con qualche problema di tenuta atletica), lascia presagire che il pron
ostico verrà rispettato. I campioni in carica non sembrano avere crepe e il loro nuovo acquisto Grellier sembra un mostro. Per il momento pero, in testa ci sono gli Yubikai (Che a pari punti hanno una miglior differenza reti rispetto ai profs.) che hanno giocato una partita entusiasmante con ben quindici gol di cui cinque appannaggio di Ruggeri, saldamente in testa alla c
lassifica. Con 26 reti, è questo il girone più prolifico, con un numero di realizzazioni superiore due volte a quello del girone B e tre volte a quello del girone C .\n\nGruppo B:\nLa situazione è molto favorevole ai Chrismateras Stars, che partiti con poche ambizioni, e il nome lo dimostra, si sono ritrovati di colpo saldamente in testa alla classifica. Complici, la vitt
oria a tre punti e la scarsa tenuta atletica dei Porci che si fanno rimontare tre gol. Gli Alka Seltzer, poi, non approfittano dello sbandamento generale dei loro avversari. Un po\' più di lucidità e di esperienza avrebbe consentito loro di tornare a casa con il carniere pieno. D\'altro canto, i Chrismateras sono riusciti a vincere di misura con i Ploucs grazie alla vena 
di Boublil, autore di una doppietta. La squadra dei fratelli Ugolini è però attesa ad una conferma il 9 ottobre contro gli Alka.\n\nGruppo C:\nIn ogni campionato che si rispetti esiste un girone di ferro, nel quale esiste equilibrio ad alti livelli. Noi speriamo di poter continuare a vedere partite come quelle di mercoledì 12 perché siamo rimasti impressionati; a parte il
 big match eccezionale tra gli S.P.Q.R e i Barjots, due tra le tre squadre più forti, due sicure pretendenti al titolo, siamo rimasti piacevolmente sorpresi dal gioco macinato dai The Angels, partiti come "numero 4" del girone, e che ora si ritrovano in testa anche se solo in virtù dei gol fatti. Il pericolo, per le prime due è come sempre quello di sottovalutarli. I Barj
ots mi assicurano che loro rispettano ogni avversario, vedremo...\n\n## IL GOL DELLA GIORNATA: GRELLIER (Il primo dei tre)\n\n![img-1.jpeg](img-1.jpeg)\nin suorame per la guasinò\ndal divagare, ma, a causa di uno\nspaccare di giunio, ma è stato\nponibile neppure è sigunaio.', images=[OCRImageObject(id='img-1.jpeg', top_left_x=203, top_left_y=1894, bottom_right_x=674, bott
om_right_y=2135, image_base64=None)], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=3, markdown="# YUBIKAI - RINKO BOYS 11-4 \n\nDopo un inizio fulmineo dei Rinko Boys, gli Yubikai replicano facendo piovere una serie di gol edibile soprattutto grazie a Ciccio Uberti ed allo gnomo laziale (per gli amici David). Il primo tempo è ricco 
di occasioni mentre il secondo è stato abbastanza noioso. In definitiva, una partita discreta con 15 gol.\n\n## YUBIKAI\n\n## DECROIX Jean-Paul $6 \\pm$ :\n\nPartenza in salita per J-P che subisce un gol dopo meno di un minuto. Decroix si riscatta in seguito e salva varie volte la sua squadra effettuando delle belle parate. J-P subisce in totale 4 gol di cui 2 da incolpev
ole e uno passatogli in mezzo alle gambe.\n\n## BRAL Éric 7 :\n\nNel primo tempo Bral opera come difensore fisso, impedendo agli attaccanti di spingersi verso la sua porta. Si spinge anche in avanti facendo un gran gol al $7^{\\circ}$ minuto. Nel secondo tempo scambia il suo ruolo di difensore con quello di attaccante di David Ruggeri. Una bella partita da parte sua.\n\n#
# RUGGERI David 7 :\n\nRuggeri in questa partita utilizza le sue migliori doti calcistiche: gran velocità e pressing continuo, inoltre utilizza la sua statura e agilità in modo intelligentesuperando in dribbling vari avversari. Va a segno per ben 5 volte dando una mano a una squadra con tanti nomi ma con poco gioco di squadra.\n\n## BEYE Amadou 6- :\n\nNon possiede una gr
an tecnica ma anche lui fa la sua parte in questa partita facendo anche un gol. Come mi ha detto lui stesso, non gioca da più di tre anni (e si vede!!! ) È un giocatore sprecone, sbaglia conclusioni semplici.\n\n## UBERTI Pablo 6+ :\n\nUberti lascia il ruolo di portiere a JeanPaul Decroix e si dedica ad azioni offensive. Combatte come un leone mettendo a segno una triplet
ta ma sbagliando tante occasioni da gol. Come prime partita nel ruolo di attaccante, Pablo Uberti se la cava più che bene.\n\n## MARSAN Stephan 6+ :\n\nArriva in ritardo alla partita perché l'autobus sul quale viaggiava ha preso fuoco (sic!). Entra in campo all'ottavo minuto del secondo tempo, si dà subito da fare pressando molto e utilizzando il suo fisico possente. Fa u
n gol allo scadere del tempo regolamentare e dà un assist a Ruggeri permettendogli di fare la cinquina.\n\n## RINKO BOYS\n\n## BRANCATI Carlo 6 :\n\nÈ l'autore del gol al primo minuto, che porta clamorosamente in vantaggio i Rinko (bel nome, complimenti!). Ha disputato una buona partita dimostrandosi molto altruista e preciso nei passaggi. Una tiratina d'orecchi perché qu
alche volta rimane fisso in attacco quando potrebbe dare una mano ai suoi in difesa.\n\n## MARENCO Toni 6+ :\n\nUna buona partita anche per lui. Mette a segno una doppietta che sa di opportunismo, ma anche di abilità tecnica. Purtroppo Toni ci sembra un po' lezioso ogni tanto e talvolta anche impreciso sottoporta però bisogna dire che si sfianca in un pressing continuo e 
proficuo e che ritorna sempre in difesa quando serve.\n\n## DIOUF Pape 5,5 :\n\nCi è parso volenteroso, desideroso di mettersi in mostra, però ha denunciato qualche insicurezza sui fondamentali, il che ha pregiudicato gravemente il voto malgrado il gol segnato. Da portiere ci ha deliziato con delle prese aeree degne del miglior Michael Jordan. Non basta per un 6.\n\n## CA
NTILENA Michele 5,5 :\n\nMichele ce la mette tutta, però commette qualche errore di troppo anche se si vede che la stoffa c'è. Ha fatto vedere qualche buona cosa per cui siamo sicuri che si rifarà, il 6 non è troppo lontano.\n\n## LEONETTI Raphaël 5 :\n\nPeccato, peccato perché il nostro Leonetti ha secondo noi i mezzi per sfondare. Dotato di buona tecnica, potrebbe fare 
grandi cose. Invece si perde in un bicchier d'acqua, spreca palloni giocabili per eccesso di egoismo e rende ancor più difficile un compito già improbo per i poveri Rinko.\n\n## SHIRIF Mahmoud 5,5 :\n\nSi è notato poco, forse perché è stato più degli altri in panchina. Tuttavia ci è parso volenteroso e discretamente efficace in copertura. Da rivedere.", images=[], dimensi
ons=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=4, markdown='# PORCI - ALKA SELTZER 5-5 \n\nInizio travolgente dei Porci che si portano rapidamente sul 5-1. Intanto crescono gli Alka che nel grazie a delle ingenuità del Busby portiere si portano sul 5-5. Partita divertente tra una squadra (i che punta molto sul fisico e un\'altra (gli Alka) c
he invece punta di più sul collettivo, mostrando già in affiatamento. Un pareggio che non accontenta nessuna delle due.\n\n## PORCI\n\nAPOLLONJ Valerio 6,5 :\nGioca una discreta partita unendo forza fisica e buona tecnica. Segna un gol al $10^{\\circ}$ e trende una traversa di testa durante una ricambolesca azione nel secondo tempo. Un 6,5 in merito al grande lavoro di co
rsa svolto.\nBALDANZA Davide 6,5 :\nAnche lui punta molto sul fisico, punto forte in comune di tutta la squadra, ma la tecnica e discreta. Va in gol 3 volte, al $2^{\\circ}$, al $14^{\\circ}$ e al $3^{\\circ}$ del secondo tempo ed è sempre partecipe a tutte le azioni di gioco pericolose della sua squadra.\nBECCALI Luca 5,5 :\nAnche lui fisicamente imponente e di buona tec
nica ma questa partita la gioca francamente male. Sbaglia un gol già fatto nel primo tempo, ne subisce uno al $6^{\\circ}$ del secondo tempo. Una prova però non totalmente negativa dato il fatto che corre molto, anche se un po\' lentamente, e si reca in aiuto dei compagni in attacco.\nBUSILY Daniel 5 - 9 :\nParte portiere ma non sembra sinceramente il suo ruolo perché sub
isce quattro dei cinque gol. soffre particolarmente il ritorno finale degli Alka seltzer, e pecca di ingenuità quando al $17^{\\circ} \\mathrm{st}$ dopo una sortita non rientra per tempo e incassa un gol da Mieli, seguito da due di Giagni. Fa comunque qualche bella parata. Il 5 è dato al suo lavoro da portiere. Perché quando esce è un vero dramma per gli Alka Seltzer. Dri
bbla, anticipa, corre, contrasta, tira, ruba palloni, interviene in attacco e in difesa, segna anche un bel gol, e si propone continuamente dalle parti di Fiorenza. Una vera spina nel fianco per Talarico e Cina quando si posta in attacco, una muraglia insormontabile per Giagni, Ribeiro e Mieli in difesa. Un 9 per tutto cio.\n\n## DI FELICE Gianluca 6 :\n\nSenza mettersi m
ai in mostra, svolge il suo lavoro discretamente, mettendola sul piano fisico soprattutto, non ha illuminazioni geniali ma neanche grosse sbavature.\n\n## PUGLIESE Francesco 6,5 :\n\nUn grande lavoro sia in copertura che in fase di attacco, sfrutta il suo fisico e gioca tantissimi palloni, pressa molto. Gioca molto bene.\n\n## ALKA SELTZER\n\n## FIORENZA Andrea 6+ :\n\nUn
 infortunio in avvio di gara ne condiziona sicuramente il rendimento. Anche se incolpevole sui gol è però insicuro in alcuni rinvii ed indeciso in qualche uscita. Da registrare comunque due buoni interventi su tiri ravvicinati (uno dei quali lancia il contropiede del primo gol). Lascia il campo alla fine del primo tempo a causa della forte contusione alla mano.\n\n## CINA
 Rodrigo 5,5 :\n\nUn primo tempo da dimenticare sia quando gioca nel ruolo da attaccante che quando gioca in quello di difensore (un paio di suoi errori offrono chiare occasioni da rete agli avversari). Cresce assieme alla squadra nella ripresa, concedendo poco o niente in fase difensiva. Nel finale è sacrificato in porta.\n\n## RIBEIRO Rodrigo 6,5 :\n\nAnche per lui un p
rimo tempo deludente caratterizzato da gravi errori in fase di disimpegno e di impostazione. È però un Ribeiro trasformato quello che scende in campo nella ripresa presidiando la difesa con grande autorità ed intelligenza. È stato fondamentale il suo apporto per la rimonta finale. Da sottolineare il suo "look" da vero professionista.\n\n## GIAGNI Mattia 7,5 :\n\nÈ lui il 
leader della squadra e si vede. Oltre alle tre splendide reti (tra le quali quella del definitivo pareggio). È l\'ispiratore della doppietta di Mieli. Da notare anche un buon pressing ed un costante apporto in fase difensiva specialmente nel primo tempo. Da segnalare un notevole interesse di Treilles nei suoi confronti...\n\n## MIELI Valerio 6,5 :\n\nSi può senz\'altro di
re, del suo primo tempo, che, se non ci fosse stato, non se ne sarebbe accorto nessuno, si riscatta invece nella ripresa nella quale va a segno due volte mettendo in mostra, nel primo caso, la sua potenza, e nel secondo il suo opportunismo.\n\n## TALARICO Mariano 5 :\n\nDue grandi botte da fuori sono le uniche note positive di una prestazione comunque al di sotto delle su
e possibilità. Una giornata negativa dovuta alla tensione che gli ha impedito di giocare con la sua abituale disinvoltura. Siamo però convinti che nella prossima gara si riscatterà dimostrando tutto il suo carisma e la sua classe.', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=5, markdown='# PROFS - DIVINA COMMEDIA 7-5 \n
\nLa partitissima del girone A nasce sotto buoni auspici. Nel primo tempo infatti le due compagini si affrontano a viso eno dimostrando di essere due valide pretendenti al titolo. In effetti i Divina riescono temporaneamente a limitare il potente acco dei Profs andando all\'intervallo in vantaggio 5 a 4. Nella ripresa invece, monologo dei Profs che vanno a segno enutament
e mettendo a nudo alcune difficoltà di tenuta atletica dei Divina che falliscono importanti azioni di contropiede.\n\n## PROFS\n\n## ANGELETTI 6 :\n\nPartita dal doppio volto per questo simpatico surveillant. Combina poco nel primo tempo quando i divina giocano meglio, poi, nel momento migliore dei Profs si esibisce nel pezzo forte del suo repertorio: il tiro per affossar
e con un gol sotto porta al $39^{\\prime}$ le speranze di pareggio dei D.C\nMENTZER 6 :\nSi vede poco in questo match, fa qualche buona cosa all\'inizio. Riappare nel momento caldo della partita quando segna un bel gol di potenza scagliato da una decina di metri che Firmani non può trattenere.\n\n## GRELLIER 8 :\n\nUn mito, onnipresente non sbaglia un colpo mettendo in ri
salto una proprietà di palleggio sorprendente ed una progressione inarrestabile. Segna ben 3 gol. Indimenticabile il primo, defilato sulla destra egli fa partire un missile da 15 m di distanza che s\'insacca sotto il sette.\n\n## TREILLES 7 :\n\nOttima partita del nostro capellone prof di gym. Fa tutto bene, esibendosi in particolare in qualche triangolazione eccezionale,
 una delle quali finalizzata con un bel gol, una bomba precisa sull\'angolo basso alla destra della porta difesa da Firmani.\nPORTAY $5++$ :\n\nQuesto simpatico professore di storia tifoso di Boksic, del croato ha ben poco. Certo è molto volenteroso e questo gli vale il primo + però ciò non basta a colmare delle evidenti lacune tecniche. Di lui ricordiamo solo un gran lan
cio per Mentzer che gli vale il secondo +. Lo aspettiamo ad una riprova.\n\n## DIVINA COMMEDIA\n\n## FIRMANI 6 :\n\nSe non teniamo conto dell\'infinita serie di urla possiamo definire buona la prestazione di Federico. Alcune buone parate, uscite un po\' avventurose, mai un grosso errore nei rilanci. Si fa però trafiggere ben 7 volte.\n\nCELI $\\boldsymbol{6}+$ :\nPartita 
sicura, senza colpi di genio ma senza errori. Si vede poco anche se è quello che corre con maggiore impegno. Ci sembra il più zolenteroso della squadra. Dovrebbe essere sêvito meglio.\n\n## MUZIO 6 :\n\nPer una volta Marco non si macchia di quello che in gergo calcistico vengono chiamate "cappelle". Alcuni bei tiri, pressing e una sicurezza massiccia in difesa.\n\n## TRIM
ANI 7- :\n\nBravissimo tecnicamente, non è come al solito troppo egoista. Dribbla fino ad arrivare al goal o a perdere palla. Comunque ottime alcune idee, tra cui delle combinazioni con Nervegna. Suo il primo gol dei D.C\nNERVEGNA 7 :\nTutte le azioni passano da lui. Elegante fino ad essere lezioso, imposta, difende, segna e fa segnare. Se corresse un po\' di più e fosse 
un po\' più umile meriterebbe un voto ancora più alto.\n\n## SFARA 6,5 :\n\nTecnicamente poco brillante ma almeno in questa occasione d\'un grande opportunismo che lo porta a segnare tre gol. Tocca pochi palloni (i maligni direbbero tre) ma fa appieno il suo lavoro. Esordiente in questo torneo, si domostra inserito nella compagnia dei D.C. Sicuramente più competitivo del 
nostro amico Caliendo.', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=6, markdown="# COMPOSIZIONE DELLE SQUADRE ISCRITTE AL TORNEO \n\n| GIRONE A |\n| :-- |\n| Profs |\n| ANGELETTI |\n| GRELLIER |\n| MENTZER |\n| PORTAY |\n| TREILLES |\n| Divina Commedia |\n| CELI M. |\n| FIRMANI F. |\n| MUZIO M. |\n| NERVEGNA A. * |\n| S
FARA P. |\n| TRIMANI P. |\n| Yubikai |\n| BEYE A. |\n| BRAL E. |\n| DECROIX J.P. |\n| GHALLOUDI O. |\n| MOSSERI G. |\n| RUGGERI D. |\n| UBERTI P. |\n| Rinko Boys |\n| BRANCATI C. |\n| CANTILENA M. |\n| DIOUF P. |\n| GOODWIN J. |\n| LEONETTI R. |\n| MARENCO A. |\n| RUFFO P. |\n| Black Eagle |\n| CHIAVE G. |\n| DELUCCHI C. |\n| GUATTERI G. |\n| PAJOU L. |\n| PROSCIA L: |\n\
n\n| GIRONE B |  |\n| :--: | :--: |\n|  | Porci |\n|  | APOLLONJ F. |\n|  | BALDANZA D. |\n|  | BECCALI L. |\n|  | BUSBY D. |\n|  | DI FELICE G. |\n|  | PUGLIESE F. |\n| Alka Seltzer |  |\n|  | CINA R.* |\n|  | FIORENZA A. |\n|  | GIAGNI M. |\n|  | MIELI V. |\n|  | RIBEIRO R. |\n|  | TALARICO M. |\n| Chrismateras Stars |  |\n| BOUBLIL D. |  |\n| CALIENDO D. |  |\n| LAZZAR
INI A. |  |\n| PAGNINI M. |  |\n| TOUBOULIC A. |  |\n| UGOLINI F.* |  |\n| UGOLINI L. |  |\n| Ploucs |  |\n|  | CAPEZZUOLI G. |\n|  | FLERI F. |\n|  | FLERI R. |\n|  | GUERIN G. |\n|  | SABATINO R. |\n| Napalm |  |\n|  | ABBRUZZETI |\n|  | BEN AMEUR |\n|  | D'AYALA * |\n|  | DE MATTOS |\n|  | PURI PURINI |\n\n\n| GIRONE C |  |\n| :--: | :--: |\n|  | S.P.Q.R. |\n| COMPAGNA
 F. FLORIDI A. LORIEDO M. NAPOLITANO N. SCADUTO C. VETRANO F. |\n| Barjots |  |\n|  | BEN REDJEB C. |\n| BEN REDJEB S. CARLONI F. CASSINI A. GALLAND B. KEITA K. STOCCHI F. |\n| Curva Nord |  |\n|  | BRUNO M.* |\n|  | LE HENAFF Q. |\n| MESCOLINI C. |  |\n| PAJOU L. |  |\n| POGLIANI G. |  |\n| SCHINCHI M. |  |\n| The Angels |  |\n| BACCARI |  |\n| CARPI |  |\n| ONORATO |  |
\n| ORTOLANI |  |\n| PUGLIESE |  |\n| SCALABRINI |  |\n| Grung |  |\n| BEN TCHEB Y. |  |\n| CAPPELLO C. |  |\n| FIORE E. |  |\n| GIGOTTI D.M. |  |\n| SAKOFF A. |  |\n| SANGES F. |  |\n| VASELLI U. |  |", images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=7, markdown='# REGOLAMENTO UFFICIALE \n\n## Articolo 1:\n\nUna squadra non
 può partecipare al torneo se non a fornito al professore responsabile i seguenti documenti:\n\n- Una scheda d\'iscrizione (una per squadra).\n- Un certificato medico per ogni giocatore, permettendo la pratica del gioco del calcio.\n- Una quota per l\'Associazione Sportiva ( 20.000 lire per giocatore.)\n\n\n## Articolo 2:\n\nUna squadra incompleta può cominciare una parti
ta inserendo nelle proprie fila giocatori appartenenti ad altre squadre a patto che:\n\n- Il giocatore esterno prenda il posto del portiere.\n- I giocatori esterni siano al massimo 2. Costoro usciranno in caso di arrivo dei titolari.\n\nUna squadra darà forfait se non può presentare meno di 3 giocatori titolari e 2 esterni all\'ora prevista dal calendario. (Delle modifich
e saranno possibili solo dopo accordo tra i due capitani delle squadre impegnate e il professore responsabile.)\n\n## Articolo 3:\n\nIl professore responsabile si riserva il diritto di espellere per una o più partite un giocatore a causa del suo cattivo comportamento in campo.\n\nLa selezione per il torneo internazionale terrà conto delle seguenti qualità dimostrate negli
 incontri del torneo del Lycée:\n\n- Qualità fisiche e tecniche del giocatore.\n- Spirito sportivo. (Fair play, rispetto delle regole, dell\'arbitro...)\n- Atteggiamento positivo nella squadra (relazioni con i compagni.)\n- 200.000 lire da versare in comode rate sul conto corrente 24508 del Credito Italiano di Roma.\n\nSpero che il torneo si svolga nella maniera migliore 
e che termini come l\'anno scorso. Amorevolmente, J.E.T.\n\n## CALENDARIO\n\n| PRIMA GIORNATA |  |\n| :--: | :--: |\n| 5 Ottobre 1994 |  |\n|  | Yubikai - Rinko Boys |\n|  | Porci - Alka Seltzer |\n|  | Profs - Divina Commedia |\n| 12 Ottobre 1994 |  |\n|  | Chrismateras Stars- Ploucs |\n|  | Curva Nord - The Angels |\n|  | S.P.Q.R. - Barjots |\n\n\n| QUARTA GIORNATA |  |
\n| :--: | :--: |\n| 30 Novembre 1994 |  |\n|  | Rinko Boys -Black Eagle |\n|  | Profs - Yubikai |\n|  | Porci - Chrismateras Stars |\n| ? Dicembre 1994 |  |\n|  | Alka Seltzer - Ploucs |\n|  | The Angels - Grunges A.C. |\n|  | S.P.Q.R. - Curva Nord |\n\n\n| SECONDA GIORNATA |  |\n| :--: | :--: |\n| 19 Ottobre 1994 |  |\n|  | Divina Commedia - Yubikai |\n|  | Profs - Blac
k Eagle |\n|  | Porci - Napalm |\n| 9 Novembre 1994 |  |\n|  | Alka Seltzer - Chrismateras Stars |\n|  | Barjots - Curva Nord |\n|  | S.P.Q.R. - Grunges A.C. |\n\n\n| QUINTA GIORNATA |  |\n| :--: | :--: |\n| 14 Dicembre 1994 |  |\n|  | Divina Commedia - Rinko Boys |\n|  | Chrismateras Stars - Napalm |\n|  | Yubikai - Black Eagle |\n| 21 Dicembre 1994 |  |\n|  | Ploucs - N
apalm |\n|  | Curva Nord - Grunges A.C. |\n|  | Barjots - The Angels |\n\n\n| TERZA GIORNATA |  |\n| :--: | :--: |\n| 16 Novembre 1994 |  |\n|  | Divina Commedia - Black Eagle |\n|  | Profs - Rinko Boys |\n|  | Porci - Ploucs |\n| 23 Novembre 1994 |  |\n|  | Alka Seltzer - Napalm |\n|  | Barjots - Grunges A.C. |\n|  | S.P.Q.R. - The Angels |\n\nQuanto al seguito del torne
o, non esiste tuttora una soluzione definitiva. IIT (macroscopico il suo errore: due volte Napalm in ultima giornata!), interpellato più volte dalla redazione ha cosi risposto:\n"Quest\'anno partecipano al torneo 15 squadre e non siamo sicuri dell\' equilibrio dei valori in campo. Per ogni girone, per esempio il primo, abbiamo messo una testa di serie (Profs), una squadra
 già presente in scorso anno (Divina Commedia), una squadra con qualche Première o Terminales (Yubikai), e due squadre prevalentemente di Seconde. Per evitare un dislivello troppo forte abbiamo pensato di fare dopo i giorni, due tornei paralleli: uno giocato dalle prime due di ogni girone, e un\'altro dalle terze e quarte classificate, in modo che tutti abbiano le stesse 
opportunità di giocare. In fondo a noi quello che importa è far giocare molte partite e che il livello espresso in campo sia buono."', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=8, markdown='# CHRISMATERAS STARS - PLOUCS 3-2 \n\nIl tempo di sistemarci in tribuna (quella accanto ai cessi) ed ecco che arriva la mitica Tri
glia, iperattiva come al solito per quamo riguarda il calcio, urlante e bella incazzata, pare per la disorganizzazione dei Ploucs (a proposito, è un nome che gli ha dato JET in persona, dopo che avevano consegnato la scheda senza nome. Però, evoca...) arrivati in ritardo alla partita. Ora secondo il nostro umile parere, a causa di atti censurabili consumatisi durante la m
attinata dati i profondi solchi sotto gli occhi. Dopo aver imparato a memoria i nomi di questi nuovi giocatori, con grande fatica ma con professionalità applicata, assistiamo con ansia al calcio d\'inizio.\n\nBasteranno poi solamente cinque minuti per capire che sarà una partita da coppa del Nonno. Da segnalare il vantaggio siglato da Boublil subito al terzo minuto e il p
areggio di Guerin per i Ploucs al $13^{\\circ}$. La Triglia cerca altri interessi e si gasa facilmente quando riceve una busta con dentro TUTTI i certificati medici con TUTTI i soldi TUTTI in una sola volta da parte degli Eagles e gli concede cosi la Palme d\'Or. A noi non resta che inchinarci e fare onore a questi Eagles (Chissà chi sono?) (Probabilmente i Black Eagle, n
dr) Nel secondo tempo i due gol, da una parte e dall\'altra, di Ugolini I e la pronta risposta di Fieri F. ristabilisce una situazione di parità. Infine un bel gol di Boublil a 2 minuti dalla fineconcede la vittoria ai Chrismateras Stars che si aggiudicano cosi una partita... ad essere sinceri mediocre.\n\n## CHRISMATERAS STARS\n\n## LAZZARINI VITI Andrea 6,5 :\n\nPara mo
lto ma non gli arrivano certo tiri irresistibili. Incolpevole sul secondo gol, è però incerto nell\'uscita che precede il primo. Da notare gli ottimi rilanci con i quali tenta di vivacizzare le lentissime azioni offensive della squadra.\n\n## UGOLINI Francesco 6:\n\nHa il merito di segnare un gol e di contribuire quindi al risultato finale. Purtroppo, come per Caliendo, d
obbiamo sottolineare la scarsa rapidità che lo svantaggia in fase difensiva (anche se non sfigura mai). Ci è parso trascurato più degli altri in panchina e non ne capiamo le ragioni considerando le opache prestazioni di alcuni individui.\n\n## CALIENDO Dario 5+:\n\nSe non fosse per la sua esasperante lentezza si meriterebbe forse anche la media ma rallenta la manovra offe
nsiva della squadra in modo da renderla prevedibile ed impacciata. In fase difensiva è praticamente inesistente anche se si è distinto per un recupero che per poco non si tramutava in autogol. Si rende comunque protagonista di un paio di bei passaggi in profondità.\n\n## PAGNINI Mattia 6+:\n\nUna buona gara in fase difensiva mettendo in mostra discrete qualità tecniche e 
tattiche. Non dà invece mai il suo appoggio in fase offensiva rimanendo fisso in difesa, forse fin troppo. Macchia la sua prestazione rendendosi colpevole del secondo gol subito dalla sua squadra.\n\n## TOUBOULIC Arnaud 6+:\n\nSi distingue dagli altri per la sua generosità nel rincorrere tutti i palloni. E tradito però dalla tecnica spesso pesante e imprecisa. Suoi comunq
ue un tiro all\'incrocio dei pali ed un assist che Boublil non raccoglie per un pelo. Non si smentisce nelle sue entrate sulle gambe.\n\n## BOUBLIL Didier 6,5:\n\nÈ il migliore della sua squadra e lo dimostra segnando il gol della vittoria. Suo anche il primo gol al $3^{\\circ}$ minuto dall\'inizio. Commette però un paio di errori solo davanti alla porta che gli abbassano
 il voto. Resta comunque l\'elemento più importante ed imprevedibile della sua squadra.\n\n## UGOLINI Lorenzo 6:\n\nÈ il punto di riferimento dal centrocampo in su ma sbaglia fin troppo suscitando numerosissimi "Mamma mia!" dalle folte "tribune". Manda in gol il fratello ma non riesce a trovare la soddisfazione personale sbagliando clamorosamente in certe occasioni. Per m
igliorare dovrebbe quindi concentrarsi di più sulla precisione evitando, a volte, dribbling incerti.\n\n## PLOUCS\n\n## SABATINO R. 7,5 :\n\nIl portiere-capitano dei Ploucs permette alla sua squadra di perdere con un briciolo di dignità. Salva infatti il risultato in ben cinque occasioni e commette una sola papera. Si aggiunge cosi un altro nome alla lunga lista dei candi
dati al posto di portiere per la nazionale.\n\n## FLERI R. 6:\n\nUn grande temerario della difesa ploucchiana che corre tantissimi rischi portando su la palla, avventandosi in improbabili dribbling. E comunque efficace in difesa se solo si limitasse a questo suo ruolo.\n\n## FLERI F. 7:\n\nÈ l\'unico pericolo considerabile per la squadra avversaria. Ha grinta, porta su la
 palla... ma è riuscito a mangiarsi ben quattro palloni d\'oro. Manca dunque l\'attaccante a cui può passare la palla per il gol. E stato poi premiato da un gol molto bello.\n\n## GUERIN G. 6:\n\nSembra il grande incompreso di questa partita... ci prova ma non ci riesce però si vede che potrebbe. Non riesce a dialogare con il resto della squadra ma suo il merito e la sigl
a del primo gol dei Ploucs.\n\n## CAPEZZUOLI G. 5+:\n\nÈ deciso, grintoso... direi quasi un gasato. Ha un bel tocco, sa dribblare ma si scorda troppo spesso che ci sono altri 4 giocatori nella sua squadra. Può dunque sembrare uno sbruffone con una disperata voglia di protagonismo ma noi sappiamo che non è cosi. E comunque sicuro che Capezzuoli è la personalità di questa s
quadra. Osiamo dunque un piccolo consiglio al nostro caloroso amico: "A Guido, sta\' calmo!"\n\n## Arbitro: NAPOLITANO 7:\n\nUn facile arbitraggio anche se una sua interruzione durante un\'azione fallosa, snobbando dunque la regola del vantaggio, può ricordare ai veterani del calcio del Lycée il nostro vecchio, mitico, ineguagliabile Fievez. Diciamo dunque grazie a Napoli
tano che ha fatto rivivere in noi vecchi ricordi. Infine è con un pizzico di nostalgia che gli diamo 7.', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=9, markdown='# CURVA NORD - THE ANGELS: 2-3 \n\nPartita condizionata oltremodo dal caso Sfara-Pajou. In effetti, Laurent Pajou figura in due squadre: i Curva Nord e i Black
 Eagle. ragglunno in fretta e furia dal nostro inviato, ci ha fatto sapere di sentirsi in tutto e per tutto un Black Eagle. Mercoledì era quindi\ninvalente assente per questa partita. Cosa hanno pensato allora Bruno e compagni? Siccome non potevano far giocare giocatori di altre\nsquadre se non in porta, e siccome loro avevano già un portiere, e Sfara era disponibile, han
no fatto registrare a Treilles il caro Pillo col nome\ndi Pajou. La partita è cominciata quindi con Pillo in attacco a fare sfracelli. Era un vero terrore per la difesa Angelina. Poi a un certo punto Treilles si deve essere detto: "Ehi! Ma quello io lo conosco." E vorrei vedere! Nella partita Profs - Divina Commedia il caro Pillo con la sua maglia ufficiale (DC) gli ha se
gnato una tripletta. Risultato: Sfara in porta e Bruno fuori. Imutile dire che ciò ha assai inciso nella prestazione dei Curva Nord, che, andati in gol per primi grazie ad una prodezza balistica di Pogliani, si fanno rimonare e poi superare. Lo stesso Giovanni pareggia, inutilmente perché Scalabrini segna il gol che sancisce la definitiva vittoria degli Angels, squadra mo
lto affiatata e molto ben messa in campo, con un collettivo da far paura. Consigliamo agli S.P.Q.R. e ai Barjota di non prenderti sottogamba.\n\n## CURVA NORD\n\n## SFARA 7+:\n\nE onnipresente. Durante i pochi minuti in campo, è l\'anima della squadra. Difende, rilancia ed in un paio di occasioni sa trovarsi puntuale al tiro. Anche in porta si difende bene ed è incolpevol
e sui gol. Purtroppo non è ai livelli di Caliendo ormai una leggenda nel giuoco del pallone, ma l\'impegno e le doti tecniche ci sono. Purtroppo per i Curva Nord, Pillo si trova già in una squadra molto più competitiva.\n\n## POGLIANI 7+:\n\nOttimo primo tempo malgrado qualche sbavatura. Corre come un treno e segna uno splendido gol su punizione. Una ripresa molto incosta
nte alternando grandi cose, come il gol, a cavolate immani. Preso dai riflessi baskettari, infatti, raccoglie in aria la palla con le mani, incorrendo nell\'espulsione temporanea durante la quale gli svversari mettono a segno il primo gol. Commette anche un brutto fallo nel finale causato sicuramente dalla stanchezza.\n\n## SCHINCHI 5,5:\n\nUn vero peccato! Rovina una buo
na prova con un\'espulsione: è l\'errore che ha consentito agli Angels di realizzare il gol della vittoria. Deve migliorare in attacco e a centrocampo dove permangono molte lacune. Può comunque migliorare applicandosi di più.\n\n## MESCOLINI 4,5:\n\nNon esiste. Corre per il campo senza meta anzi vagabonda. Non infieriamo troppo per non demoralizzarlo ma il suo impegno nel
 calcio è da rimettere in discussione. Insomma una bella perna de pau.\n\n## BRUNO 4,5:\n\nLo distinguiamo da Mescolini perché lui nemmeno corre. Però, almeno, lui ha due scusanti: la eterna imperfetta forma fisica (Gli consigliamo una bella dieta) e l\'indonestà della posizione in campo. In effetti, lui che doveva giocare in porta si trova spaesato lì sulla fascia dove o
ccupa più che altro la posizione dello zoppo. Sul finale, Pugliese gli nega un gol già fatto.\n\n## THE ANGELS\n\n## PUGLIESE 6+:\n\nNon corre grandissimi pericoli, specialmente nel primo tempo, grazie all\'ottima prova della difesa. Nell\'intervallo, pensavo sinceramente di mettergli un bel SV che avrebbe gratificato il reparto arretrato di questa squadra. Sulla punizion
e magistrale di Pogliani, comunque, non era piazzato benissimo. Ad ogni modo non si può giudicare la partita di un giocatore da un singolo episodio, senza contare che punizioni così, già non escono spesso in serie A, figurarsi a questi livelli. Nel secondo tempo la musica cambia, con i Curva Nord decisi ad acciuffare il pareggio, compie qualche buon intervento. Fa il mira
colo su tiro di Bruno, che aveva approfittato di una sua uscita avvenitata, che gli vale il + .\n\n## ORTOLANI 6,5:\n\nÈ l\'unico a non avere una posizione fissa in campo. Corre tantissimo e sostiene il reparto che ha più bisogno di lui. Partecipa in maniera attiva all\'avvolgente manovra difensiva che nega più volte la conclusione alle punte "nordiste". Il suo apporto in
 fase di costruzione e di impostazione è lodevole. Ha costruito alla base la vittoria degli Angels.\n\n## CARPI 7+ :\n\nSe gli attaccanti dei Curva Nord non sono riusciti a segnare se non su calci piazzati o su vere intuizioni è stato soprattutto merito della difesa e, quindi, del suo massimo rappresentante: Alessandro Carpi. Costui ha quasi annientato l\'azione di Pillo 
Sfara quando costui era in campo, costringendolo a concludere malamente le proprie azioni. Pogliani lo fa un po\' soffrire ma grazie all\'aiuto dei compagni (vedi Ortolani) permette a Pugliese di godersi la partita da spettatore. Il + , manco a dirlo, è per il gol, coliegina sulla torta, giunto a coronamento di una prova superlativa.\n\n## COLOMBO s.v.:\n\nEntra oramai a 
giochi fatti. Non stona, il che vuol dire che il suo livello è buono. Lo aspettiamo ad una conferma. Dopo il turno di riposo che la squadra dovrà effettuare nella seconda giornata, l\'attendono gli S.P.Q.R (23:11); in quella partita, oltre a verificare l\'effettivo valore della squadra, potremo vedere all\'opera (speriamo un po\' più a lungo) questo giocatore.\n\n## BACCA
RI 7:\n\nLa difesa "nordista" non se lo scorderà facilmente. Nel primo tempo, infatti, Schinchi e compagni hanno dovuto superarsi per negargli il gol. In virtù anche dei numerosi assist ricevuti, ha giocato numerosi palloni. Ha fatto un paio di cappelle che avrebbero dovuto portare a un -, ma il Ct ci ha fatto sapere che a lui non importava...\n\n## SCALABRINI 7,5++ :\n\n
I due + rappresentano ovviamente i due gol. Ciò vuol dire che il voto in sé, se lo è costruito diversamente. È l\'uomo ovunque di questa squadra malgrado giocasse con una vistosa fascistura alla mano. Le cose più belle le ha fatte vedere nel primo tempo proponendo tanti e invitanti palloni a Baccari. Nella ripresa segna e fa segnare attirando l\'attenzione di Treilles il 
che fa ben sperare per il suo futuro in "nazionale".', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=10, markdown='# S.P.Q.R. - BARJOTS 2-1 \n\nDue grandi squadre dedite allo spettacolo hanno dato a tutti i giocatori delle partite precedenti una dimostrazione di come gioca a calcio. Dopo un pomeriggio caratterizzato da cat
enaccio e pochi gol, (in tutto 13 contro i 37 del primo mercoledì), una ma accesi i riflettori, la gente che fino a quel momento sbadigliava, si è potuta finalmente divertire. La caratteristica tecnica minante del match è stato il confronto tra una squadra grimosa e concreta (gli S.P.Q.R.) e da una invece assai spettacolare ma so efficace sotto porta (i Barjots). Si tratt
a comunque, e si sapeva, delle maggiori indiziate tra le pretendenti al titolo.\n\n## S.P.Q.R.\n\n## FLORIDI Alessandro 7:\n\nAnche se bombardato dai tiri di Keita, Floridi ha saputo opporsi all\'attacco avversario. Da notare al $17^{\\circ}$ del secondo tempo una grande uscita sullo stesso Keita lanciato a rete da Ben Redjeb. Deve però arrendersi a Stocchi che dopo una m
ischia in area conclude a rete con un tiro al volo.\n\n## VETRANO Fabrizio 6+:\n\nImpiggato in difesa a contrastare il grande Ben Redjeb Jr., Vetrano si è comportato bene. Spesso sbaglia i lanci ma si riscatta con dei tiri molto potenti che intimoriscono i Barjots. Unica nota negativa: un tris di "Che cazzo!" decisamente inutile.\n\n## SCADUTO Christian 8:\n\nE onnipresen
te in campo, sia in attacco che in difesa. Dotato di un tiro considerevole, Scaduto si è espresso bene. Da notare al $13^{\\circ}$ del secondo tempo un suo vero siluro che ha fatto tremare la porta degli avversari. Suo l\'assist del primo goal.\n\n## NAPOLITANO Nicolò 6,5:\n\nGrande nella fascia difensiva, Napolitano ha saputo al meglio contrastare l\'offensiva dei Barjot
s spesso ricorrendo a qualche fallo. Sbaglia un goal a tu per tu con il portiere come solo Darko Pancev lo avrebbe potuto sbagliare. E lui a segnare il raddoppio degli S.P.Q.R. con un siluro da fuori area in semirovesciata che si è insaccato sotto al sette. Decisamente un buon inizio di campionato per lui.\n\n## LORIEDO Mario 7:\n\nSe non avesse segnato il goal del vantag
gio degli S.P.Q.R. non si sarebbe certamente meritato un voto simile. Ha sbagliato troppo e spesso si è lanciato in dribblings inutili. Questo mercoledì non si è espresso al meglio ma siamo sicuri che ci farà vedere il suo calcio migliore.\n\n## COMPAGNA Francesco s.v.:\n\nInfortunato, gioca due o tre minuti alla fine. Per il momento funge da mascotte.\n\n## BARJOTS\n\nCA
RLONI Francesco $6,5++$ :\n\nOvviamente incolpevole sui gol, specie sul secondo, vera e propria intuizione Napolitana, dimostra di essere una sicurezza. Da notare due provvidenziali interventi al $2^{\\circ} \\mathrm{st}$ su Loriedo e, in uscita, al $10^{\\circ} \\mathrm{st}$ sempre su Loriedo e su Scaduto. Sono i due +\n\n## GALLAND Baptiste 6,5:\n\nIl suo lavoro in dife
sa è stato fondamentale. Divide con Carloni e Cassini il merito di un passivo così basso (se pensiamo al 10 a 1 dell\'anno scorso...). Recupera davvero molti palloni e li smista in avanti senza sbagliare un passaggio. Un\'ottima partita. Chiude a rete una serie di triangolazioni con Cheb e Cassini. Troppo poco per un + .\n\n## CASSINI Alessandro 7:\n\nCome Galland è impas
sabile in difesa. Più di Galland è concreto nelle sue sortite offensive. Ad ogni avanzata fa paura. E uno dei pochi Barjots che poteva segnare. In particolare al $10^{\\circ} \\mathrm{pt}$ prende la trversa su gran colpo di testa.\n\n## BEN REDJEB Sinen 6,5-:\n\nAvevamo in un primo tempo pensato di mettergli 6 , in quanto la sua prestazione non offriva grandi spunti di cr
onaca. Però riconosciamo la sua grandissima tecnica e la sua enorme umiltà, impensabile a questi livelli. Si sacrifica per la squadra correndo come un forsennato. Tiene alto il livello del match. Non ha lampi, gli costa il -\n\n## BEN REDJEB Cheb 7:\n\nTutte le azioni passano da lui. Sulla fascia sinistra è una specie di irriducibile guerriero. Tecnica elevata, senso tatt
ico molto sviluppato grazie anche al grande affilatamento della squadra, da molti anni sulle scene. E lui il principale assist-man della squadra. Ne confezions parecchi, in particolare per Kader.\n\n## KEITA Kader 7:\n\nPrestazione ambigua. Tecnicamente eccellente. Tocchi di classe, di fino, di tacco, di testa... pretende di avere sangue brasiliano e ne ha motivo. Stesse 
qualità (spettacolo, classe, dribbling...) stessi difetti: una mancanza di concretezza esasperante. Quando dicevamo di Cassini, "uno dei pochi che poteva segnare" vuol sottolineare come Kader, schierato come punta, puntava a tutto meno che alla porta. E comunque protagonista di tantissimi episodi, specie nella ripresa dove ha avuto modo di giocare di più: $5^{\\circ} \\ma
thrm{st}$ : doppio tiro pericoloso. $7^{\\circ} \\mathrm{st}$ : spreca un assist prezioso di Cheb tirando al volo di destro quando di sinistro non avrebbe avuto problemi ad insaccare. Egizodio, al $19^{\\circ} \\mathrm{st}$ per il quale meriterebbe un applauso ed una tirata d\'orecchi. Scaglia da quindici metri, da posizione difficilissima un pallone che va ad insaccarsi 
sotto al sette a portiere battuto. Peccato però che dal fallo laterale non si possa tirare in porta. E simbolo della squadra perché poco concreto ma altamente spettacolare.\n\n## STOCCHI Francesco 7:\n\nMi dispiace di dover restringere la sua pagella per mancanza di spazio, me ne scuso con Francesco, perché è l\'unico elemento in contraddizione pura col resto del gruppo. 
Guarda caso è lui, al $19^{\\circ} \\mathrm{st}$ ad accorciare le distanze dopo aver tentato un tiro da posizione difficile già un minuto prima. Un finale in crescendo. Poco gioco, molti tiri, un gol.', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654)), OCRPageObject(index=11, markdown='# FLASH DE LA COUR \n\n## CASSINI SEGNA UN GOL A MARSAN\n\nSc
rano episodio nell\'incontro disputato sabato 8 ottobre a meccingiorno: Alessandro Cassini, il portierone dei Barjots e della sccomale, si è tolto per una volta i guanti per segnare un gol su regare all\'attaccante degli Yuhikai, Stephan Marsan, aggiudicandosi co: l\'ambito titolo di capoclasse della Ta.\n\nL\'ala sinistra della squadra di Marsan, Joshua Pelosi, ha più "c
he contestato l\'arbitro, accusato di favorire in maniera eccessiva il Alessandro nazionale. Eppure il match si era messo amarsana male per la sua squadra. Uno svolgimento alquanto smento del primo tempo ha portato, alla sua chiusura, ad una spemorità numerica della compagine capitanata da Marsan di ben 10 m 9. Ma alla fine Cassini si è imposto di misura. Da registrare gr
ande abbraccio tra i due capitani che ha placato un po\' gli animi piutosto roventi.\n\nMarsan, comunque, lamentava l\'assenza per infortunio del Sornclasse Grenat, il quale, secondo lui, avrebbe senz\'altro fatto rendere la bilancia dalla sua parte.\n\nBALBO-FONSECA SURCLASSATI DA MIELI-GOL.\nAncora una volta i gemelli del gol soccombono alla classe degli sversari. Duran
te la gara del $11 / 10$, in salle 16 presieduta dall\'arbitro Lise Poueng (per gli amici lose Poueng Poueng) da Perpignan.\n\nBailo e Fonseca mettono a segno una doppetta ma ciò non basta a superare le 17 naffitate di Mieli stento nel primo tempo e le 9 di Cabriel nel secondo.\n\nPer chi avesse capito poco del testo precedente, si rivolga a quei coglioni che alle elezion
i del délégué de classe di 1a hanno votato Ballo-Fonseca.\n\n## HANNO DETTO:\n\nVista la rottura di coglioni, durante la partita (Chiamataras Stars-Ploucs) ci siamo permessi di distrarci prendendo nota di tutte le frasi famose della partita. E così che abbiamo fatto una lista, con il pronto aiuto dell\'inviato cappellate Guy Mosseri, di citazioni, frasi famose, detti, ins
omma delle cavolate che si riescono a dire intorno ad una partita di pallone.\n\nCAPEZZUOLI I: (ricevendo una palla) "Bella \'sta palla, mi gasa."\n\nFLERI: "Bella portie\', ti amo" (con conseguente sguardo impaurito del nostro povero Sabatino.)\n\nMOSSERI: (a Capezzuoli che si rimette a posto gli occhiali dopo una pallonata in faccia) "C\'ha gli occhiali storti!"\n\nCASS
INI: "Un po\' come il suo ca...o."\nCAPEZZUOLI II: (Con occhiali storti) "Vedo doppio!" TREILLES: (a Capezzuoli) "Ne discute pas; t\'es payé pour jouer même si tu n\'es pas payé."\n\nKEITA: "Rimani se vuoi vedere un po\' di spettacolo\nveri."\nSINEN: (Per la serie: non siamo razzisti) "On a préféré jouer avec Kader car la nuit on ne levoit pas.\n\nDAVID: Allors è meglio A
madou."\nDAVID: (inno di Curva Nord-The Angels, dopo dieci mami ancora 0 a 0 . Treilles si accorge del caso Pillo.) "Pourquoi ils ont arrêté le jeu?\n\nSINEN: -Parce que Treilles leur explique qu\'on peut marquer des buts."\n\nUGOLINI: "Pourquoi vous avez deux gardiens (Cassini a Carloni) dans votre équipe?\n\nSINEN: -Parce que on les enleve aux adversaires."\n\nE per fin
ire il consiglio più prezioso che la vecchia gestione ha voluto offrire alla nuova redazione:\n\nCOMPAGNA: "Tutto il segreto sta nel trovare il braccio. Niccol Napolitano, che lavora, lavora e batte senza arrendersi, e (indicando sé stesso) la mente."\n\n## UNA NAZIONALE DA RICOSTRUIRE\n\nIl lupo perde il vizio ma non il pelo infatti, probabilmente il cr della nazionale d
i Chateau continuerà ad essere Mr Treilles (il capellone per intenderci.)\n\nJet dovrà passare molte notti insonni per ricostruire una nazionale che l\'anno passato si era comportata discretamente nel torneo infrascolastico (semifinale persa ai supplementari contro St Georges); anche se i maligni ricorderebbero ben più volentieri la pessima figura fatta a Madrid.\n\nInfat
ti della nazionale dell\'anno scorso rimane ben poco e le partenze dei Scaduto, dei Busby e dei Napolitano peseranno molto, ma la Triglia con molta buona volontà riuscirà sicuramente nell\'intento di riorganizzare una squadra per il prossimo torneo.\n\nQuest\'anno Treilles ha a disposizione un parco giocatori vastissimo ( 80 ragazzi che militano in 15 squadre diverse) che
 con un po\' di fortuna gli consentirà di formare una squadra più competitiva dell\'anno scorso. L\'unico consiglio che posso dare per entrare nel giro della nazionale è quello di giocare con molta grinta ma allo stesso tempo di essere corretto nei confronti dell\'avversario.\n(Treilles .all\'inizio di ogni partita dice sempre "Les gars, je veux du fair-play")\nBuona Fort
una a tutti...\n\n## IL TIFOSO VIP:\n\nUGOLINI: "Professor Maggi, è vero che lei ha promesso di bocciare chiunque batta i Divina Commedia?\n\nMAGGI: -Sì!\nUGOLINI: -Sa da chi sono stati battuti in prima giornata? Dai professori!\nMAGGI: (Ci pensa un po\' su) -Nietzsche diceva: I professori sono talmente squallidi ch meritano veramente di essere quello che sono."\n(Dopo un
 po\' becca Celi che stava parlando.)\nMAGGI: "Marco sento di odiarti.\nUGOLINI: -Guardi che è il centravanti dei Divina Commedia.\nMAGGI: -Allora le cose cambiano."\n\nVi ricordate il mitico Pugliese, per gli amici Pille e conosciuto da tutti come "il filippoe"? Ebbene, dopo la sua partenza con il bac in mano (non si sa come abbia fatto) e la conseguente mancanza della c
aratteristica ammalenza nella scuola, abbiamo scoprato che la stirpe dei Pugliese non è ancora finita. Enote infatti un nuotolo Pille che sta già scoprendo il mondo e sembra presto a non tradire una tradizione familiare bestiale (nel vero senso della parola).\n\nDopo qualche puntura di sedativi per calmare l\'animale, siamo riusciti ad avvicinare a parte, in tutta fretta,
 qualche domanda. Ne è nata un\'improbabile intervista a un figlio d\'arte.\n\nTUTTOSTORT: - Non ti senti un po\' raccomandato?\nPOULIESE: - Queste malolagine devono solo crepare, dimostrerò a tutti che merito la mia reputazione e seguirò così le orme di mio fratello.\n\nTUTTOSTORT: - Contaoura dunque anche per te la maledizione delle scerifite continue della famiglia Pug
liese.\n\nPOULIESE: - No! Tutto tranne quello!\n(Ci allestamiamo velocemente perché la partita - Curva Nord-The Angels - sta per comunicare e l\'effetto del calmante sta per finire.\n(A fine partita, vieta dalla squadra di Pugliese 3 a 2)\nTUTTOSTORT: - Hai finalmente rotto la maledizione del re della giungla. Un commento sulla partita?\nPOULIESE: - E stata dura come un p
arto, ma ce l\'abbiamo fatta.\nNon ce la sentiamo di commentare questa risposta di Pugliese ma vorremo solo sperare che verrà posta nella Top 10 della frasi famose. Complimenti Puglie.\n\nHANNO COLLABBORATO ALLA REALIZZAZIONE DI QUESTO NUMERO:\n\nMariano TALARICO\nMarco MUZIO\nLorenzo UGOLINI\nPier Paolo SFARA\nValerio MELI\nAlessandro CASSINI\nFrancesco UGOLINI\nDario CA
LIENDO\nMichele BRUNO\nAndrea NERVEGNA\n\nLe pagelle sono rigorosamente anonime per evitare pericolose rappresaglie.', images=[], dimensions=OCRPageDimensions(dpi=200, height=2339, width=1654))] model='mistral-ocr-2503-completion' usage_info=OCRUsageInfo(pages_processed=12, doc_size_bytes=23132478)
